export const restaurants = [
    {
      id: "1",
      name: "Burger Palace",
      cuisine: "American",
      rating: 4.5,
      deliveryTime: "25-35 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "2",
      name: "Pizza Heaven",
      cuisine: "Italian",
      rating: 4.7,
      deliveryTime: "30-40 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "3",
      name: "Sushi World",
      cuisine: "Japanese",
      rating: 4.8,
      deliveryTime: "35-45 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "4",
      name: "Taco Fiesta",
      cuisine: "Mexican",
      rating: 4.3,
      deliveryTime: "20-30 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "5",
      name: "Curry House",
      cuisine: "Indian",
      rating: 4.6,
      deliveryTime: "30-45 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
    {
      id: "6",
      name: "Noodle Bar",
      cuisine: "Chinese",
      rating: 4.4,
      deliveryTime: "25-35 min",
      imageUrl: "/placeholder.svg?height=400&width=600",
    },
  ]
  
  export const menuItems = [
    // Burger Palace
    {
      id: "101",
      restaurantId: "1",
      name: "Classic Cheeseburger",
      description: "Beef patty with cheese, lettuce, tomato, and special sauce",
      price: 8.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "102",
      restaurantId: "1",
      name: "Bacon Deluxe Burger",
      description: "Beef patty with bacon, cheddar, onion rings, and BBQ sauce",
      price: 10.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "103",
      restaurantId: "1",
      name: "Veggie Burger",
      description: "Plant-based patty with avocado, sprouts, and vegan mayo",
      price: 9.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "104",
      restaurantId: "1",
      name: "Loaded Fries",
      description: "Crispy fries topped with cheese, bacon, and sour cream",
      price: 5.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  
    // Pizza Heaven
    {
      id: "201",
      restaurantId: "2",
      name: "Margherita Pizza",
      description: "Classic pizza with tomato sauce, mozzarella, and basil",
      price: 12.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "202",
      restaurantId: "2",
      name: "Pepperoni Pizza",
      description: "Pizza with tomato sauce, mozzarella, and pepperoni",
      price: 14.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "203",
      restaurantId: "2",
      name: "Supreme Pizza",
      description: "Pizza with pepperoni, sausage, bell peppers, onions, and olives",
      price: 16.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "204",
      restaurantId: "2",
      name: "Garlic Bread",
      description: "Freshly baked bread with garlic butter and herbs",
      price: 4.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  
    // Sushi World
    {
      id: "301",
      restaurantId: "3",
      name: "California Roll",
      description: "Crab, avocado, and cucumber wrapped in seaweed and rice",
      price: 7.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "302",
      restaurantId: "3",
      name: "Spicy Tuna Roll",
      description: "Spicy tuna and cucumber wrapped in seaweed and rice",
      price: 8.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "303",
      restaurantId: "3",
      name: "Dragon Roll",
      description: "Eel and cucumber topped with avocado and eel sauce",
      price: 12.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "304",
      restaurantId: "3",
      name: "Miso Soup",
      description: "Traditional Japanese soup with tofu and seaweed",
      price: 3.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  
    // Taco Fiesta
    {
      id: "401",
      restaurantId: "4",
      name: "Beef Tacos",
      description: "Three corn tortillas with seasoned beef, lettuce, and cheese",
      price: 8.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "402",
      restaurantId: "4",
      name: "Chicken Quesadilla",
      description: "Flour tortilla filled with chicken, cheese, and peppers",
      price: 9.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "403",
      restaurantId: "4",
      name: "Veggie Burrito",
      description: "Large flour tortilla with beans, rice, veggies, and guacamole",
      price: 10.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "404",
      restaurantId: "4",
      name: "Nachos Supreme",
      description: "Tortilla chips topped with beans, cheese, jalapeños, and sour cream",
      price: 7.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  
    // Curry House
    {
      id: "501",
      restaurantId: "5",
      name: "Chicken Tikka Masala",
      description: "Grilled chicken in a creamy tomato sauce with spices",
      price: 13.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "502",
      restaurantId: "5",
      name: "Vegetable Biryani",
      description: "Basmati rice cooked with mixed vegetables and aromatic spices",
      price: 11.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "503",
      restaurantId: "5",
      name: "Butter Naan",
      description: "Soft flatbread brushed with butter",
      price: 2.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "504",
      restaurantId: "5",
      name: "Samosas",
      description: "Crispy pastries filled with spiced potatoes and peas",
      price: 5.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  
    // Noodle Bar
    {
      id: "601",
      restaurantId: "6",
      name: "Beef Chow Mein",
      description: "Stir-fried noodles with beef and vegetables",
      price: 11.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "602",
      restaurantId: "6",
      name: "Kung Pao Chicken",
      description: "Spicy stir-fried chicken with peanuts and vegetables",
      price: 12.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "603",
      restaurantId: "6",
      name: "Vegetable Spring Rolls",
      description: "Crispy rolls filled with cabbage, carrots, and mushrooms",
      price: 4.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
    {
      id: "604",
      restaurantId: "6",
      name: "Hot and Sour Soup",
      description: "Spicy and tangy soup with tofu, mushrooms, and bamboo shoots",
      price: 3.99,
      imageUrl: "/placeholder.svg?height=300&width=400",
    },
  ]
  